-- Дополнительные поля новой ID-карты.
ALTER TABLE state ADD COLUMN IF NOT EXISTS surname TEXT NOT NULL DEFAULT '';
ALTER TABLE state ADD COLUMN IF NOT EXISTS sex     TEXT NOT NULL DEFAULT '';
ALTER TABLE state ADD COLUMN IF NOT EXISTS expiry  TEXT NOT NULL DEFAULT '';
